# Generated by Django 4.2.3 on 2023-08-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.DecimalField(decimal_places=2, max_digits=9)),
                ('HRA', models.DecimalField(decimal_places=2, max_digits=9)),
                ('TA', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTwo.employee')),
            ],
        ),
    ]
